TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB_INSTALLS += devagilent3631A.db
# FIXME -- HOW TO INSTALL agilent3631A.proto????
# Install the Prototype file alongside the database files
DB_INSTALLS += $(TOP)/agilent3631ASup/devagilent3631A.proto

#=======================================
include $(TOP)/configure/RULES
